# Generated by Django 3.2.7 on 2021-09-29 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='ENG', max_length=3, verbose_name='язык пользователя'),
        ),
    ]
