# Generated by Django 3.2.7 on 2021-10-03 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'M'), ('W', 'W')], default=None, max_length=2, null=True, verbose_name='пол'),
        ),
    ]
